# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 409f64127b9ff7fb80a3cdfe4457b7d97a51c41f9be90bc65ef3c7fea271cee8a4817bee4f026714237728d4a68ef9999b1c815aaf010e416a13222bc0b566ed

test:
  secret_key_base: b310993b25751badef2a4ac74698ce40274f893b48eed2fbf865b10fc134401affc8f1a51fb7fd45d29b66228993c227d7b3325e674d11df0bcb68129313a6b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
