# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8be412d475352c13e042a7db871f62911f5f89a5afac99790adf4757a3db95d5c3263bd6db11b07159f1caaabb97d4e33afcfc1d93880d330c4a82d077cadba0

test:
  secret_key_base: 50cd97fa901e900a598a945a3962f45fb1d1ecb6e8b723c6ed905b8b665779ef7982130d3fcd618b933dbf27ed7e499d3a8a55f74a6fc0d9a0a4f70875384f8e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
